### ISSUE TITLE
Verbose provisioning

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/hydroform#103]
**Description**
The provision call of the provision library is a blocking call giving no further in-between status. In case of strange behavior, it will be great to have a way of retrieving the internal logs of the command to be used as verbose logs. Maybe improve the interface to attach a log stream to the stdout of the client in case verbose logging is wanted.

**Reasons**
Often the provisioning call just executes giving no details on whats happening and even on the cloud provider side nothing is happening. So having a verbose mode indicating that a terraform-provider gets downloaded will help to understand whats going on.

**Attachments**

**Comment by clebs** [comment]
This was solved in https://github.com/kyma-project/hydroform/issues/252
