### ISSUE TITLE
parallel-installation lib wrong kubeconfig configuration

### ISSUE THREAD

**Issue by strekm** [kyma-project/hydroform#157]
**Description**

Kubernetes client is configured in 2 places in the library: one is a client used in prerequisites and another one is a client used in helm client. The first client is created using kubeconfig provided by user via kubeconfig flag, the second one is created with exported KUBECONFIG environment variable. This can lead to confusion. 

**Expected result**

Both kubernetes clients are created with the same kubeconfig file.

**Actual result**

Two different kubeconfig files are used for deploying kyma.

**Steps to reproduce**

1. export KUBECONFIG=file_1.yaml
2. go run example.go --kubeconfig file_2.yaml

**Troubleshooting**

**Comment by clebs** [comment]
This issue is no longer valid, the parallel installation module has been removed.
