### ISSUE TITLE
Support passing inline credentials to the Provider struct

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/hydroform#16]
**Description**

The only way to pass credentials to the `Provider` struct is by using `CredentialsFilePath` field. This makes it really inconvenient to use when operating on just the file contents.   

**Reasons**

Passing path to the credentials is very inconvenient to use when working with only the contents of such file. It requires the library user to create some file only for a time of provisioning.

There should be the ability to pass credentials in the form of credentials file content as a byte array.

**Attachments**

**Comment by clebs** [comment]
Hi @Szymongib,
thanks for the feedback. It is definitely something we would like to add to hydroform, I will add this to our backlog.

**Comment by Szymongib** [comment]
Hi @clebs,
Thanks for the response, looking forward to that feature.

**Comment by a-thaler** [comment]
We will not work on that
