### ISSUE TITLE
New Installation: Check component pending state when upgrading

### ISSUE THREAD

**Issue by clebs** [kyma-project/hydroform#196]
**Description**
Currently, the installation logic either installs a component that is not there, or it upgrades it if it exists.
This causes a failed upgrade in case the component that is being upgraded is actually still installing.

Before upgrading a component, check if it is done installing or not. In case it isn't don't upgrade it and track its progress.

**Reasons**
Avoid failed upgrades when a component is still installing.

**Comment by tobiscr** [comment]
Seems we our current logic isn't covering the edge-case that a deployment was interrupted. In such cases, a rollback should happen to the last consistent state (interesting reads: https://stackoverflow.com/questions/65006907/kubernetes-helm-stuck-with-an-update-in-progress + https://github.com/helm/helm/issues/8987#issuecomment-742086773).
