### ISSUE TITLE
New installation: Add overrides for certificates chart

### ISSUE THREAD

**Issue by colunira** [kyma-project/hydroform#208]
**Description**

- [ ] Add override `global.newInstallation` set to true
- [ ] Add override `global.ingress.domainName` set to the same value as `global.domainName`

**Reasons**

This change is required for the [new way of cert-management](https://github.com/kyma-project/kyma/issues/10336) to work in parallel with the old approach. Implementing this issue and https://github.com/kyma-incubator/hydroform/issues/187 will allow the removal of fetching overrides from the CM in the cluster in the parallel installation library.

When we get rid of old installation and remove the `global.ingress.domainName` these overrides can be removed.

**Attachments**
https://github.com/kyma-project/kyma/issues/10297

**Comment by strekm** [comment]
`ingress.domanName` interceptor is already implemented
