### ISSUE TITLE
New installation: Handle resources (CRDs) uninstallation

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-project/hydroform#214]
**Description**

Provide implementation in installation lib that covers uninstallation of resources (such as CRDs). Have a look at `PreInstaller` struct.

**Reasons**

Follow-up to #177 in which we do not provide uninstallation strategy.

**Comment by strekm** [comment]
consult @pbochynski whether we want to introduce labeling CRDs to be able to remove them without the need of downloading kyma sources.

**Comment by clebs** [comment]
CRDs are now removed completely when uninstalling .
