### ISSUE TITLE
Provision: Add debug option

### ISSUE THREAD

**Issue by clebs** [kyma-project/hydroform#252]
**Description**

Sometimes, to debug issues, the current verbose mode on the provisioning is not enough to find out the real problems.

Add an option to the provision API to allow to print all debug logs from terraform.

**Reasons**

Improve debugging capabilities.

**Comment by elchead** [comment]
What should be done other than https://github.com/kyma-project/cli/issues/882 ?

**Comment by clebs** [comment]
That is all. First this issue needs to be finished and afterwards https://github.com/kyma-project/cli/issues/882

**Comment by elchead** [comment]
A verbose option has been added to output terraform logs

**Comment by elchead** [comment]
A verbose option has been added to output terraform logs
