### ISSUE TITLE
Git tests in parallel-install take too much time

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-project/hydroform#260]
**Description**

Tests from `hydroform/parallel-install/pkg/git/` take too long. They are unit tests, so they should take at most a few seconds. On my local machine when they are not cached they take roughly 90-100 seconds. On pipelines it is even 200-300 seconds.

**Expected result**

These tests should either take at most a few seconds (which is still a lot in comparison to other tests) or be turned off or testes once for a while.

**Actual result**

Local machine:

<img width="785" alt="Screenshot 2021-04-14 at 20 32 39" src="https://user-images.githubusercontent.com/14920383/114882329-20a9f880-9e04-11eb-92b1-9d96650fee4e.png">

Pipeline:

<img width="998" alt="Screenshot 2021-04-15 at 16 00 40" src="https://user-images.githubusercontent.com/14920383/114882520-52bb5a80-9e04-11eb-8133-e0ae37c59151.png">

**Steps to reproduce**

Run `go test -v ./...` in `parallel-install` or trigger the build on pipeline.

**Troubleshooting**

As suggested, maybe remote repository that is being downloaded should be changed to the smaller one.

**Comment by skhalash** [comment]
After minor code refactoring it's possible to unit test the package without doing expensive network calls. It now takes <1 sec to run the package tests.
