### ISSUE TITLE
parallel-install: Improve pre-installation API

### ISSUE THREAD

**Issue by clebs** [kyma-project/hydroform#265]
**Description**

The public API for doing the pre-installation tasks is leaking implementation details to the client and requires a big amount of code to use:
https://github.com/kyma-project/hydroform/blob/5cd78b98a7f1bddf8021037af92a716979cdd6e2/parallel-install/example/example.go#L90-L117

Refactor the API so that it can be used with more simple calls and hydroform does the heavy lifting.

**Reasons**

Improve dev experience and reduce mistakes.

**Comment by Tomasz-Smelcerz-SAP** [comment]
👍

**Comment by clebs** [comment]
Issue is no longer valid, parallel installation package was deprecated and removed long ago.
