### ISSUE TITLE
Rollback/uninstall failed components

### ISSUE THREAD

**Issue by colunira** [kyma-project/hydroform#272]
**Description**

If a component fails to install, it should be either uninstalled or rollbacked to the latest revision before the next retry.

**Reasons**

Helm has problems with installing/upgrading components that are in a Failed state, so retries may be useless if we do not retrieve a proper status of a component.

**Comment by pbochynski** [comment]
Uninstall only during provisioning (first install). During upgrade it doesn't make sense.

**Comment by Tomasz-Smelcerz-SAP** [comment]
At this moment we're switching to reconciler project for Kyma installation/upgrades, old method of installations are deprecated.
