### ISSUE TITLE
Parallel install: Improve concurrency model

### ISSUE THREAD

**Issue by clebs** [kyma-project/hydroform#303]
**Description**

The currently implemented concurrency on the parallel installation works as follows:
- It creates a batch of X parallel workers that each install 1 component (being X the configured concurrency).
- Wait for all workers to finish.
- Create again X workers with 1 component each.
- Wait for all workers to finish again.
- Repeat

This approach is not effective because:
- Faster workers in each batch will be idle waiting for slower ones to finish (e.g. if 1 worker needs 3 min and the rest need 10 seconds, all workers except 1 will be doing nothing for 2min and 50 seconds).
- Creating new worker instances over and over is unnecessary.
- Arbitrary batches could cause hard to solve bugs.

**Proposal**
A more effective way would be using the `worker pool concurrency` model:
- Put all components from the component list in a channel
- Create X workers all having access to the shared channel and wait for them
- Each worker picks a component from the channel and deploys it
- When finished it picks up another component from the channel
- When channel is empty it means all work is done and worker finishes

This would guarantee that workers are always doing work and the configured concurrency (X) is constantly kept. Additionally workers need to be created only once.

**Reasons**

Better concurrency giving much faster installation times.

**Attachments**
See this sample implementation in Go of the worker pool model:
https://gobyexample.com/worker-pools

**Comment by a-thaler** [comment]
Overall implementation changes so that this ticket is not applicable anymore
