### ISSUE TITLE
Parallel install sends ProcessUpdate event after installation completed

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/hydroform#316]
**Description**

While testing Provisioner with parallel-install library ([PR-678](https://github.com/kyma-project/control-plane/pull/678)) I noticed a crash in callback method handling ProcessUpdate from `parallel-install`. After some investigation it turned out that `parallel-install` sent an update event after the installation was marked as complete what in turn caused Provisioner's crash. Apart from incorrect `ProcessUpdate` callback implementation in Provisioner, parallel-install should not emit events after installation completed. 

**Expected result**

There is no `ProcessUpdate` sent after one of the following cases is true:
- all components installed
- one of the events occurred: ProcessExecutionFailure, ProcessForceQuitFailure, deployment.ProcessTimeoutFailure.

**Actual result**

There is a ProcessUpdate event sent.

**Steps to reproduce**

It was reproduced under load on Provisioner - there were 10 concurrent provisioning processed at the same time.

**Comment by clebs** [comment]
This issue is no longer valid, the parallel installation module has been removed.
