### ISSUE TITLE
Integrate gardener terraform module

### ISSUE THREAD

**Issue by clebs** [kyma-project/hydroform#93]
**Description**
When there is an available gardener terraform module, integrate it into Hydroform and get rid of the hardcoded template.

**Acceptance criteria**
- Gardener module is integrated and all target providers supported.
- Old template is removed and not needed anymore.

**Extra info**
- This issue needs to be done after #92
- For an implementation example, please see azure module integration: #78

**Comment by a-thaler** [comment]
We will not invest further here
